name: intake-dcat
channels:
  - conda-forge
  - informaticslab
dependencies:
  - python=3
  - geopandas
  - intake=0.4.4
  - intake_geopandas=0.2.0
  - jupyterlab
  - pip:
    - git+https://github.com/dask/dask@master
