name: intake-dcat
channels:
  - conda-forge
dependencies:
  - python=3
  - geopandas
  - intake=0.4.4
  - jupyterlab
  - pip:
    - git+https://github.com/dask/dask@master
    - git+https://github.com/ian-r-rose/intake_geopandas@multiple-input-sources
