name: intake-dcat
channels:
  - conda-forge
  - informaticslab
dependencies:
  - descartes
  - geopandas>=0.5
  - intake>=0.5.0
  - intake_geopandas>=0.2.2
  - matplotlib
  - python=3
  - pip:
    - intake-dcat
    - jupyterlab
